### ISSUE TITLE
No negated methods on base '_' object

### ISSUE THREAD

**Issue by constantijnherpers** [unnoon/bottom_line#2]
In the readme.md docs it says:

"Negated methods

For readability every method can be negated by prefixing not.

arr._.has('elm1'); // normal call

arr._.not.has('elm1'); // negated form"

But for the base "_" object the 'not' property does not exist. So sadly I can't do "_.not.isFunction()".

**Comment by unnoon** [comment]
ok should be fixed in version 0.0.8

**Comment by unnoon** [comment]
Fixed in version 0.0.8. See unit test in unit/global.js
